### ISSUE TITLE
Extending the application resolver

### ISSUE THREAD

**Issue by martin-hoger** [BBVAEngineering/ember-cli-custom-addons#1]
Hi there,

first of all, thank you for the plugin. Unfortunately I have problems to resolve the files from the addon directory. In my dist/assets/app.js I see correctly included:
define('dummy/components/foo', ['exports'....

The default resolver would not look in the addons directory, so I need to extend it, right? Can you give me a hint/help how to do that?

Thank you very much!

**Comment by josex2r** [comment]
Hi Martin.

Currently, the ember resolver only import modules with a namespace matching the property `modulePrefix` defined when instancing the resolver (`config/environment.js`).

You have to extend the methods that use the namespace to match all ocurrences (`custom-addons` directories names).

We will try to publish our resolver asap :)

**Comment by martin-hoger** [comment]
Thank you very much for the fast response. I will try extend it but I am not sure if it is not too high level for an Ember newbie.

**Comment by josex2r** [comment]
Try using this addon:

https://github.com/BBVAEngineering/ember-cli-awesome-resolver
